#!/bin/bash

#module load python/3.7.5
#module load gcc/8.3.0
#module load boost/1.7.0

if [ ! -d gt4py ] ; then
  git clone https://github.com/GridTools/gt4py.git
fi

python -m venv venv
source venv/bin/activate
pip install numpy matplotlib
pip install -e ./gt4py

