#!/bin/bash

dir=`readlink -f $0`

# make sure we are using the right modules
module purge
source ${dir}/module_env

# create virtual environment for workshop
if [ -f venv ] ; then
  ln -s /home/twicki/venv .
fi
source venv/bin/activate

# install venv as ipython kernel
python -m ipykernel install --user --name venv --display-name "workshop"

# install ipython profile for MPI
ipython profile create --parallel --profile=mpi
cp ./setup/ipcluster_config.py ~/.ipython/profile_mpi/

# deactivate virtual environment
deactivate

echo "Setup for DSL workshop successfully completed."
